### ISSUE TITLE
Add ignoreAreas into testRun payload 

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/sdk-java#38]
New property is added `ignoreAreas` into request payload and could be processed by server side: https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/132
Add ability to pass it as parameter into `track` method to ignore some parts of image

```
class IgnoreArea {
  x: int;
  y: int;
  width: int;
  height: int;
}

```
![1](https://user-images.githubusercontent.com/5182956/97895465-7d28c800-1d3c-11eb-8692-2da34e7ad156.png)

**Comment by pashidlos** [comment]
@alexromanov would you like to take it?

**Comment by alexromanov** [comment]
Start working.
