### ISSUE TITLE
Add ciBuildId into create build request

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/sdk-java#42]
New field was added ins cope of https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/142 and will be used as a glue to build in CI 

Create build payload 
```
{
  "ciBuildId": "string",
  "branchName": "string",
  "project": "string"
}
```

TODO:
* Add optional field `ciBuildId` into config object 
* send field in create build request
* add field into response

**Comment by alexromanov** [comment]
I'll take it.
