### ISSUE TITLE
Property name doesn't match API contract

### ISSUE THREAD

**Issue by wasder** [Visual-Regression-Tracker/sdk-java#44]
https://github.com/Visual-Regression-Tracker/sdk-java/blob/8d342c8ca5261575a67eaea94bf065c31ceec574/src/main/java/io/visual_regression_tracker/sdk_java/TestRunOptions.java#L16

![image](https://user-images.githubusercontent.com/2205216/99429472-206f0500-2919-11eb-888f-14cfebd4436e.png)

**Comment by pashidlos** [comment]
It needs to be renamed into `ignoreAreas`
