### ISSUE TITLE
Fork 4.5.3 as android-sdk

### ISSUE THREAD

**Issue by benquinteros** [Visual-Regression-Tracker/sdk-java#58]
IMU android can only use up to java 8, with the java 11 refactor in 5.0.0, I've had to use 4.5.3 for compatibility. 

Is there any plans to maintain this version / spin it off into it's own repo? 

Cheers

**Comment by pashidlos** [comment]
@benquinteros thanks for the info, as I understand it's a blocker for you 
so far there is no functional difference between `4.5.3` and `5.0.0` and all basic functionality is implemented

adding of new features will be up to `sdk-java` maintainers team 

let me investigate if we could make code compatible with java 8 with the help of this https://github.com/bsideup/jabel

**Comment by pashidlos** [comment]
@Visual-Regression-Tracker/sdk-java is any of you using java 8?
what do you think about maintaining specifically java 8?

**Comment by suratdas** [comment]
For my understanding - when we say Android, are we talking about an issue with appium java library or espresso? Appium which has selenium dependency already supports Java 11 per comment https://github.com/SeleniumHQ/selenium/issues/7021#issuecomment-492264311 
Is the problem seen while using an older version of selenium library incompatible with Java 11 ?

**Comment by benquinteros** [comment]
Hello, I'm talking about espresso ( 3.3.0 ) in this case :)

**Comment by suratdas** [comment]
@benquinteros This is what I do for espresso. I do not run visual comparison during the test run for various reasons. After the test run is finished, I use adb pull command to get all screenshots on my computer and then run the VRT comparison as a separate step (example https://github.com/Visual-Regression-Tracker/examples-java/tree/master/standalone-from-folder-maven). This helps me in faster test execution, decide whether to go with VRT depending on the number of test failures, etc. This way, I can also re-use the same VRT SDK comparison module for my XCUITest for iOS devices too.
I tried before with espresso( 3.0.1) and Java 8 and did not try recently. Could you please confirm if the approach I described above will work for you and if this approach helps you in achieving what you wanted?

**Comment by benquinteros** [comment]
I've gotten this working in my test environment by implementing 

https://developer.android.com/studio/write/java8-support

Thanks @suratdas for the snippet, may need to implement that in future but for now this works for me.

As I am using 4.5.3, I'm assuming future vrt updates (5.0+) will break this version 😢
